# Crowdin configuration file
# https://support.crowdin.com/configuration-file/

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        ja: ja
        ko: ko
        zh-CN: zh
        th: th
        es-ES: es
        vi: vi
